/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_client_file_upload_fileUploads_upload_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_client_file_upload_fileUploads_upload_parameter_1$schema = z.object({
  'data': z.string().readonly(),
  'name': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_client_file_upload_fileUploads_upload_result$schema = z.object({
  'receiptId': z.intersection(z.string(), z.unknown()).readonly(),
  'file': z.object({
  'attachmentId': z.intersection(z.string(), z.unknown()),
  'name': z.string(),
  'bytes': z.number(),
}).readonly(),
})

export const TYPERT_REMOTE = {
  package: '@deepseek-ai/dsh-client-file-upload',
  descriptors: [
    {
      id: '@deepseek-ai/dsh-client-file-upload#fileUploads/upload',
      service: 'fileUploads',
      namespace: 'fileUploads',
      method: 'upload',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_client_file_upload_fileUploads_upload_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-client-file-upload/types#EncodedFileUploadRequest',
            schema: _deepseek_ai_dsh_client_file_upload_fileUploads_upload_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-client-file-upload/types#FileUploadValue',
        schema: _deepseek_ai_dsh_client_file_upload_fileUploads_upload_result$schema,
      },
      sourceLocation: {"file":"packages/client/file-upload/src/index.ts","line":106,"column":3},
    },
  ],
}

export default TYPERT_REMOTE
