/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_changes_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_changes_result$schema = z.union([z.object({
  'kind': z.literal("ready").readonly(),
}), z.object({
  'kind': z.literal("change").readonly(),
  'change': z.union([z.object({
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
}), z.object({
  'absolutePath': z.string().readonly(),
  'absent': z.literal(true).readonly(),
})]).readonly(),
})])
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_parameter_1$schema = z.string()
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_result$schema = z.object({
  'path': z.string().readonly(),
  'entries': z.array(z.object({
  'name': z.string().readonly(),
  'type': z.union([z.literal("file"), z.literal("directory"), z.literal("other")]).readonly(),
  'size': z.number().readonly().optional(),
})).readonly(),
  'truncated': z.boolean().readonly(),
})
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_1$schema = z.string()
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_2$schema = z.object({
  'offset': z.number().readonly().optional(),
  'limit': z.number().readonly().optional(),
})
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_result$schema = z.object({
  'offset': z.number().readonly(),
  'text': z.string().readonly(),
  'lines': z.number().readonly(),
  'eof': z.boolean().readonly(),
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
  'bytes': z.number().readonly().optional(),
})
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_parameter_1$schema = z.string()
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_result$schema = z.object({
  'offset': z.number().readonly(),
  'data': z.string().readonly(),
  'eof': z.boolean().readonly(),
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
  'bytes': z.number().readonly().optional(),
})
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_1$schema = z.string()
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_2$schema = z.object({
  'offset': z.number().readonly().optional(),
  'length': z.number().readonly().optional(),
})
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_result$schema = z.object({
  'offset': z.number().readonly(),
  'data': z.string().readonly(),
  'eof': z.boolean().readonly(),
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
  'bytes': z.number().readonly().optional(),
})
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_1$schema = z.string()
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_2$schema = z.string()
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_result$schema = z.object({
  'offset': z.number().readonly(),
  'data': z.string().readonly(),
  'eof': z.boolean().readonly(),
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
  'bytes': z.number().readonly().optional(),
})
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_parameter_1$schema = z.string()
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_result$schema = z.object({
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
  'bytes': z.number().readonly().optional(),
})

export const TYPERT_REMOTE = {
  package: '@deepseek-ai/dsh-api-workspace-files',
  descriptors: [
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/changes',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'changes',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_changes_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileWatchFrame',
        schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_changes_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":365,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/list',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/list:path',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceDirectoryListing',
        schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":337,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/read',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'read',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/read:path',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_1$schema,
          },
        },
        {
          name: 'range',
          wire: 'range',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileRange',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_2$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileText',
        schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":232,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readAll',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'readAll',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readAll:path',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileBytes',
        schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":278,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readBytes',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'readBytes',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readBytes:path',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_1$schema,
          },
        },
        {
          name: 'range',
          wire: 'range',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceByteRange',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_2$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileBytes',
        schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":257,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readRelated',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'readRelated',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readRelated:path',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_1$schema,
          },
        },
        {
          name: 'relativePath',
          wire: 'relativePath',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readRelated:relativePath',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_2$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileBytes',
        schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":300,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/stat',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'stat',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/stat:path',
            schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileStat',
        schema: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":324,"column":9},
    },
  ],
}

export default TYPERT_REMOTE
